services:
  portal-server:
    container_name: update_pps
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: /target/update-db-for-portal-production-system-0.0.1-SNAPSHOT.jar
    env_file:
      - .env
    ports:
      - 8088:8088
    volumes:
      - spring-backups:/home/backups
      - spring-log:/home/logs
    restart: always

volumes:
  spring-log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/home/astra/logs"
  spring-backups:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/home/astra/backups"


